openapi: "3.1.0"
info:
  title: GPT Docs Generator
  version: "1.0"
servers:
  - url: https://script.google.com/macros/s/AKfycbyOdAE8AsRYgvoKwBtCVoYHvy214YWXFEHIxFoBoyo_lnflj_6tjnHtsP1Jyc61pfojlA/exec
paths:
  /:
    post:
      operationId: generateDoc
      summary: Genereer bewerkbaar .docx-leermiddelenbeleid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
              properties:
                title:
                  type: string
                content:
                  type: object
                  additionalProperties:
                    type: string
      responses:
        "200":
          description: JSON met download_url
          content:
            application/json:
              schema:
                type: object
                properties:
                  download_url:
                    type: string
